### ISSUE TITLE
Add Example Repository Button or Prefill Dropdown to Interface

### ISSUE THREAD

**Issue by nkkko** [daytonaio/devcontainer-generator#20]
**Is your feature request related to a problem? Please describe.**
New users may struggle to understand how the tool works without having an example repository to test. Providing a prefilled dropdown or a button with example repositories will make it easier for users to get started and understand the generation process without needing their own repository URL initially.

**Describe the solution you'd like**
- Add a button or dropdown to the interface that pre-fills the GitHub repository URL input with example repositories.
- This should allow users to click "Generate" without pasting their own URL, providing a quick way to see the tool in action.
- Ensure these example repositories are relevant and showcase the capabilities of the tool effectively.

**Describe alternatives you've considered**
- Providing extensive documentation on how to get started, but this may not be as engaging or immediately useful as an interactive example.
- Relying solely on user input, which could frustrate users who just want to see a quick demo.

**Additional context**
Include relevant example repositories that cover a range of common use cases. Make sure to test the functionality to ensure it's seamless and provides a good user experience. This feature will enhance onboarding and user engagement by making it easier to see the tool in action.

**Comment by mobley-trent** [comment]
Hello @nkkko I'm currently getting this error while attempting to run `Generate` for any repo:

```
Traceback (most recent call last):
  File "/workspaces/devcontainer-generator/main.py", line 112, in post
    exists, existing_record = check_url_exists(repo_url)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/devcontainer-generator/helpers/github_helpers.py", line 148, in check_url_exists
    existing = supabase.table("devcontainers").select("*").eq("url", url).order("created_at", desc=True).limit(1).execute()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/postgrest/_sync/request_builder.py", line 78, in execute
    raise APIError(r.json())
postgrest.exceptions.APIError: {'code': '42P01', 'details': None, 'hint': None, 'message': 'relation "public.devcontainers" does not exist'}
```

From my understanding the program is checking for values in a supabase db, but I didn't see any instructions for configuring supabase.

**Comment by nkkko** [comment]
Yes, readme needs to be updated, check .env example you should be able to test it with your supabase account, you just need to set it up.
